language: node_js

services:
  - docker

node_js:
    - node
    - "12"
    - "10"

cache: npm

install:
    - npm install
    - npm install -g codecov

script:
    - npm run lint
    - npm run test -- --coverage
    - npm run build
    - npm run validate:sourcemaps
    - npm run changelog
    - codecov

branches:
    only:
        - master
        - /^feature\/.*$/
        - /^bugfix\/.*$/
