import { realpathSync } from "fs";
import { resolve } from "path";

const allPossibleExistingFiles = [
	"index.test.",
	"index.test",
	"index.production.",
	"index.production",
	"index.local.",
	"index.local",
	"index.",
	"index",
	"index.test.local.",
	"index.test.local",
	"index.production.local.",
	"index.production.local",
	"index.development.local.",
	"index.development.local",
	"index.development.",
	"index.development",
	".env.test",
	".env.production",
	".env.local",
	".env",
	".env.test.local",
	".env.production.local",
	".env.development.local",
	".env.development",
	".env.test.json",
	".env.production.json",
	".env.local.json",
	".env.json",
	".env.test.local.json",
	".env.production.local.json",
	".env.development.local.json",
	".env.development.json",
	"src/index.test.",
	"src/index.test",
	"src/index.production.",
	"src/index.production",
	"src/index.local.",
	"src/index.local",
	"src/index.",
	"src/index",
	"src/index.test.local.",
	"src/index.test.local",
	"src/index.production.local.",
	"src/index.production.local",
	"src/index.development.local.",
	"src/index.development.local",
	"src/index.development.",
	"src/index.development",
	"src/.env.test",
	"src/.env.production",
	"src/.env.local",
	"src/.env",
	"src/.env.test.local",
	"src/.env.production.local",
	"src/.env.development.local",
	"src/.env.development",
	"src/.env.test.json",
	"src/.env.production.json",
	"src/.env.local.json",
	"src/.env.json",
	"src/.env.test.local.json",
	"src/.env.production.local.json",
	"src/.env.development.local.json",
	"src/.env.development.json",
	"coverage/index.test.",
	"coverage/index.test",
	"coverage/index.production.",
	"coverage/index.production",
	"coverage/index.local.",
	"coverage/index.local",
	"coverage/index.",
	"coverage/index",
	"coverage/index.test.local.",
	"coverage/index.test.local",
	"coverage/index.production.local.",
	"coverage/index.production.local",
	"coverage/index.development.local.",
	"coverage/index.development.local",
	"coverage/index.development.",
	"coverage/index.development",
	"coverage/.env.test",
	"coverage/.env.production",
	"coverage/.env.local",
	"coverage/.env",
	"coverage/.env.test.local",
	"coverage/.env.production.local",
	"coverage/.env.development.local",
	"coverage/.env.development",
	"coverage/.env.test.json",
	"coverage/.env.production.json",
	"coverage/.env.local.json",
	"coverage/.env.json",
	"coverage/.env.test.local.json",
	"coverage/.env.production.local.json",
	"coverage/.env.development.local.json",
	"coverage/.env.development.json"
];

const resolvePath = relativePath => resolve(realpathSync(process.cwd()), relativePath);

const getAbsoluteFromRelative = (relativePathTransformer = path => path) => relative =>
	resolvePath(relativePathTransformer(relative));

const comparePathArrays = relativeToAbsoluteFn => (expectedRelativePaths, actualAbsolutePaths) => {
	expect(expectedRelativePaths.map(relativeToAbsoluteFn)).toEqual(actualAbsolutePaths);
};

export { allPossibleExistingFiles, getAbsoluteFromRelative, comparePathArrays, resolvePath };
